// TypeScript migration skeleton for SignalEngine (partial types)
import { getIndicator } from './indicators/registry';

export interface Bar { symbol?:string; time:string; open:number; high:number; low:number; close:number; volume?:number }
export interface Pending { side: 'LONG'|'SHORT'; confirmationsPassed: Set<string>; startedTime:string; leadingRationale?:string; barsElapsed:number }
export interface EngineState { lastConfirmedSide: null|'LONG'|'SHORT'; pending: Pending|null; barIndex:number; history:Bar[] }
export interface SignalEngineConfig { signalExpiryCandles:number; alternateSignal:boolean; leadingIndicator:string; confirmationsEnabled:string[]; minConfluence:number; supertrend:{ period:number; multiplier:number } }

const DEFAULT_CONFIG: SignalEngineConfig = { signalExpiryCandles:3, alternateSignal:true, leadingIndicator:'Range Filter', confirmationsEnabled:['EMA200','MACD','RSI','Supertrend'], minConfluence:1.0, supertrend:{ period:10, multiplier:3 } };

export class SignalEngine {
  config: SignalEngineConfig; state: EngineState; private _emaCache: Map<number,{value:number; lastIndex:number}> = new Map();
  constructor(cfg: Partial<SignalEngineConfig> = {}) { this.config = { ...DEFAULT_CONFIG, ...cfg }; this.state = { lastConfirmedSide:null, pending:null, barIndex:0, history:[] }; }
  updateConfig(patch: Partial<SignalEngineConfig>) { this.config = { ...this.config, ...patch }; }
  getConfig(){ return this.config; }
  ingestBar(bar:Bar){ this.state.barIndex++; this.state.history.push(bar); if(this.state.history.length>5000) this.state.history.shift(); const events:any[]=[]; const leading=this.evalLeading(); const confirmations=this.evalConfirmations(); const { pending }=this.state; if(pending){ pending.barsElapsed++; const side=pending.side; const passed=this.collectPassed(confirmations, side); passed.forEach(p=>pending.confirmationsPassed.add(p)); const allSel=this.config.confirmationsEnabled; const confluenceScore=pending.confirmationsPassed.size / (allSel.length||1); if(pending.confirmationsPassed.size===allSel.length && confluenceScore>=this.config.minConfluence){ const evt=this.buildActionable(side, bar, leading, pending, confluenceScore); events.push(evt); this.state.lastConfirmedSide=side; this.state.pending=null; } else if(pending.barsElapsed>this.config.signalExpiryCandles){ events.push({ type:'expiredSetup', side, reason:'CONFIRMATIONS_TIMEOUT', leadingStartTime:pending.startedTime, barsWaited: pending.barsElapsed }); this.state.pending=null; } else if(passed.size){ events.push(this.buildWatch(side, bar, pending)); } }
    const blockLong=this.config.alternateSignal && this.state.lastConfirmedSide==='LONG'; const blockShort=this.config.alternateSignal && this.state.lastConfirmedSide==='SHORT'; if(!this.state.pending){ if(leading.longTrigger && !blockLong){ this.openPending('LONG', bar, leading.longRationale); events.push(this.buildWatch('LONG', bar, this.state.pending!)); } else if(leading.shortTrigger && !blockShort){ this.openPending('SHORT', bar, leading.shortRationale); events.push(this.buildWatch('SHORT', bar, this.state.pending!)); } } else { if(this.state.pending.side==='LONG' && leading.shortTrigger && !blockShort){ events.push({ type:'cancelledSetup', side:'LONG', reason:'OPPOSITE_TRIGGER' }); this.openPending('SHORT', bar, leading.shortRationale); events.push(this.buildWatch('SHORT', bar, this.state.pending!)); } else if(this.state.pending.side==='SHORT' && leading.longTrigger && !blockLong){ events.push({ type:'cancelledSetup', side:'SHORT', reason:'OPPOSITE_TRIGGER' }); this.openPending('LONG', bar, leading.longRationale); events.push(this.buildWatch('LONG', bar, this.state.pending!)); } }
    return events; }
  private evalLeading(){ const ind=getIndicator(this.config.leadingIndicator); if(!ind) return { longTrigger:false, shortTrigger:false }; return ind.compute(this.state, this.config); }
  private openPending(side:'LONG'|'SHORT', bar:Bar, rationale?:string){ this.state.pending={ side, confirmationsPassed:new Set(), startedTime:bar.time, leadingRationale:rationale, barsElapsed:0 }; }
  private buildWatch(side:'LONG'|'SHORT', bar:Bar, pending:Pending){ const all=this.config.confirmationsEnabled; const passed=Array.from(pending.confirmationsPassed); const missing=all.filter(x=>!pending.confirmationsPassed.has(x)); return { type:'watchOpportunity', side, status:'PENDING', time:bar.time, price:bar.close, barsSinceLeading:pending.barsElapsed, confirmationsPassed:passed, confirmationsMissing:missing, expiresInBars:this.config.signalExpiryCandles - pending.barsElapsed }; }
  private buildActionable(side:'LONG'|'SHORT', bar:Bar, leading:any, pending:Pending, confluenceScore:number){ return { type:'actionableSignal', side, status:'ACTIONABLE', time:bar.time, price:bar.close, leadingIndicator:{ name:this.config.leadingIndicator, rationale: pending.leadingRationale || (side==='LONG'?leading.longRationale:leading.shortRationale) }, confirmations:{ passed:Array.from(pending.confirmationsPassed), failed:[] }, confluenceScore, risk:this.calcBasicRisk(bar), reasonSummary:`Leading=${this.config.leadingIndicator}; Confirmations=${Array.from(pending.confirmationsPassed).join(',')}` }; }
  private calcBasicRisk(bar:Bar){ const hist=this.state.history; if(hist.length<15) return { note:'insufficient_data'}; const recent=hist.slice(-15); const atr=this.simpleATR(14); const swingLow=Math.min(...recent.map(b=>b.low)); const swingHigh=Math.max(...recent.map(b=>b.high)); return { atr, suggestedStops:{ conservative:swingLow, adaptiveATRx1_5: bar.close - (atr||0)*1.5 }, suggestedTakeProfits:[ { method:'R-multiple', R:1, level:bar.close + (atr||0)*1 }, { method:'StructureHigh', level:swingHigh } ] }; }
  private simpleATR(n:number){ const h=this.state.history; if(h.length<n+1) return null; let sum=0; for(let i=h.length-n;i<h.length;i++){ const prev=h[i-1]; const cur=h[i]; const tr=Math.max(cur.high-cur.low, Math.abs(cur.high-prev.close), Math.abs(cur.low-prev.close)); sum+=tr; } return sum/n; }
  private collectPassed(confirmations:any, side:'LONG'|'SHORT'){ const set=new Set<string>(); for(const key of this.config.confirmationsEnabled){ const k=confirmations[side.toLowerCase()][key]; if(k===true) set.add(key); } return set; }
  private evalConfirmations(){ return { long:this.evalSideConfirmations('LONG'), short:this.evalSideConfirmations('SHORT') }; }
  private evalSideConfirmations(side:'LONG'|'SHORT'){ const out:Record<string,boolean>={}; for(const key of this.config.confirmationsEnabled){ switch(key){ case 'EMA200': out[key]=this.confirmEMA(200, side); break; case 'MACD': out[key]=this.confirmMACD(side); break; case 'RSI': out[key]=this.confirmRSI(side); break; case 'Supertrend': out[key]=this.confirmSupertrend(side); break; default: out[key]=false; } } return out; }
  private confirmSupertrend(side:'LONG'|'SHORT'){ const st=this.calcSupertrend(); if(!st) return false; const last=st[st.length-1]; return side==='LONG'? last.trend==='LONG': last.trend==='SHORT'; }
  private confirmEMA(len:number, side:'LONG'|'SHORT'){ const ema=this.calcEMA(len); if(ema==null) return false; const close=this.state.history[this.state.history.length-1].close; return side==='LONG'? close>ema : close<ema; }
  private confirmMACD(side:'LONG'|'SHORT'){ const macd=this.calcMACD(); if(!macd) return false; return side==='LONG'? macd.line>macd.signal : macd.line<macd.signal; }
  private confirmRSI(side:'LONG'|'SHORT'){ const rsi=this.calcRSI(14); if(rsi==null) return false; return side==='LONG'? rsi>50: rsi<50; }
  private calcEMA(period:number){ const hist=this.state.history; if(hist.length<period) return null; const k=2/(period+1); let ema=hist[hist.length-period].close; for(let i=hist.length-period+1;i<hist.length;i++){ ema=hist[i].close*k + ema*(1-k);} return ema; }
  private calcMACD(){ const fast=12, slow=26, signal=9; const hist=this.state.history; if(hist.length<slow+signal) return null; const closes=hist.map(b=>b.close); const emaSeries=(p:number)=>{ const k=2/(p+1); let arr:number[]=[]; let ema=closes[0]; for(let i=0;i<closes.length;i++){ ema=i===0?closes[i]:closes[i]*k + ema*(1-k); arr.push(ema);} return arr; }; const ef=emaSeries(fast), es=emaSeries(slow); const macdLine=ef.map((v,i)=>v-es[i]); const kSig=2/(signal+1); let sigArr:number[]=[]; let sig=macdLine[slow]; for(let i=0;i<macdLine.length;i++){ sig=i===0?macdLine[i]:macdLine[i]*kSig + sig*(1-kSig); sigArr.push(sig);} return { line: macdLine[macdLine.length-1], signal: sigArr[sigArr.length-1] }; }
  private calcSupertrend(){ const { period, multiplier }=this.config.supertrend; const h=this.state.history; if(h.length<period+2) return null; const atr=(idx:number)=>{ if(idx<period) return null; let sum=0; for(let i=idx-period+1;i<=idx;i++){ const c=h[i]; const p=h[i-1]; const tr=Math.max(c.high-c.low, Math.abs(c.high-p.close), Math.abs(c.low-p.close)); sum+=tr; } return sum/period; }; const out:any[]=[]; let trend:'LONG'|'SHORT'='LONG'; let upper=0, lower=0, prevClose:number|null=null; for(let i=0;i<h.length;i++){ const bar=h[i]; const a=atr(i); if(a==null){ out.push({}); continue; } const mid=(bar.high+bar.low)/2; const bU= mid + multiplier*a; const bL= mid - multiplier*a; if(!upper){ upper=bU; lower=bL; } else { upper=(bU<upper || (prevClose!==null && prevClose>upper))?bU:upper; lower=(bL>lower || (prevClose!==null && prevClose<lower))?bL:lower; } let flipped=false; if(trend==='LONG' && bar.close<lower){ trend='SHORT'; flipped=true; } else if(trend==='SHORT' && bar.close>upper){ trend='LONG'; flipped=true; } out.push({ trend, flipped, upper, lower, close: bar.close }); prevClose=bar.close; } return out; }
  private calcRSI(period:number){ const hist=this.state.history; if(hist.length<period+1) return null; let gains=0, losses=0; for(let i=hist.length-period;i<hist.length;i++){ const diff=hist[i].close - hist[i-1].close; if(diff>0) gains+=diff; else losses-=diff; } const rs=gains/(losses||1e-9); return 100 - 100/(1+rs); }
  private _ema(series:number[], period:number){ if(!series.length) return NaN; let entry=this._emaCache.get(period); if(!entry || entry.lastIndex!==series.length-2){ let value=series[0]; const k=2/(period+1); for(let i=1;i<series.length;i++){ value=series[i]*k + value*(1-k);} entry={ value, lastIndex:series.length-1 }; this._emaCache.set(period, entry); return value; } const price=series[series.length-1]; const k=2/(period+1); entry.value=price*k + entry.value*(1-k); entry.lastIndex=series.length-1; return entry.value; }
}
